/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.eabsensii;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import com.mycompany.eabsensii.view.PanelKelas;
import com.mycompany.eabsensii.view.PanelMatkul;
import com.mycompany.eabsensii.view.PanelDosen;
import com.mycompany.eabsensii.view.PanelMahasiswa;
import com.mycompany.eabsensii.view.PanelJadwal;
import com.mycompany.eabsensii.view.PanelAbsensi;
import com.mycompany.eabsensii.view.PanelDashboard;


/**
 *
 * @author shaqy
 */
public class MainDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());
    CardLayout cardLayout;
    private final PanelKelas panelKelas;
    private final PanelMatkul panelMatkul;
    private final PanelDosen panelDosen;
    private final PanelMahasiswa panelMahasiswa;
    private final PanelJadwal panelJadwal;
    private final PanelAbsensi panelAbsensi;
    private final PanelDashboard panelDashboard;

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();

        cardLayout = (CardLayout) (mainPanel.getLayout());
        panelKelas = new PanelKelas();
        panelMatkul = new PanelMatkul();
        panelDosen = new PanelDosen();
        panelMahasiswa = new PanelMahasiswa();
        panelJadwal = new PanelJadwal();
        panelAbsensi = new PanelAbsensi();
        panelDashboard = new PanelDashboard();
        mainPanel.add(panelKelas, "panelKelas");
        mainPanel.add(panelMatkul, "panelMatkul");
        mainPanel.add(panelDosen, "panelDosen");
        mainPanel.add(panelMahasiswa, "panelMahasiswa");
        mainPanel.add(panelJadwal, "panelJadwal");
        mainPanel.add(panelAbsensi, "panelAbsensi");
        mainPanel.add(panelDashboard, "panelDashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDashboard = new javax.swing.JButton();
        btnMahasiswa = new javax.swing.JButton();
        btnDosen = new javax.swing.JButton();
        btnKelas = new javax.swing.JButton();
        btnMatkul = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        btnAbsensi = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Absensi Mahasiswa");
        setResizable(false);

        sidebar.setBackground(new java.awt.Color(0, 153, 153));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("E-ABSENSI");

        btnDashboard.setBackground(new java.awt.Color(0, 153, 153));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("🏠 Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnMahasiswa.setBackground(new java.awt.Color(0, 153, 153));
        btnMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnMahasiswa.setText("🎓 Mahasiswa");
        btnMahasiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnMahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMahasiswaActionPerformed(evt);
            }
        });

        btnDosen.setBackground(new java.awt.Color(0, 153, 153));
        btnDosen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnDosen.setText("👨 Dosen");
        btnDosen.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnDosen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosenActionPerformed(evt);
            }
        });

        btnKelas.setBackground(new java.awt.Color(0, 153, 153));
        btnKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnKelas.setText("🏫 Kelas");
        btnKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelasActionPerformed(evt);
            }
        });

        btnMatkul.setBackground(new java.awt.Color(0, 153, 153));
        btnMatkul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMatkul.setForeground(new java.awt.Color(255, 255, 255));
        btnMatkul.setText("📘 Mata Kuliah");
        btnMatkul.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnMatkul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatkulActionPerformed(evt);
            }
        });

        btnJadwal.setBackground(new java.awt.Color(0, 153, 153));
        btnJadwal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnJadwal.setForeground(new java.awt.Color(255, 255, 255));
        btnJadwal.setText("🗓️ Jadwal");
        btnJadwal.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnJadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });

        btnAbsensi.setBackground(new java.awt.Color(0, 153, 153));
        btnAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        btnAbsensi.setText("📋 Absensi");
        btnAbsensi.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnAbsensi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsensiActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 153, 153));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("🚪 Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDashboard)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMahasiswa)
                            .addComponent(btnDosen)
                            .addComponent(btnKelas)
                            .addComponent(btnMatkul)
                            .addComponent(btnJadwal)
                            .addComponent(btnAbsensi)
                            .addComponent(btnLogout)))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard)
                .addGap(18, 18, 18)
                .addComponent(btnMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(btnDosen)
                .addGap(18, 18, 18)
                .addComponent(btnKelas)
                .addGap(18, 18, 18)
                .addComponent(btnMatkul)
                .addGap(18, 18, 18)
                .addComponent(btnJadwal)
                .addGap(18, 18, 18)
                .addComponent(btnAbsensi)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        cardLayout.show(mainPanel, "panelDashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMahasiswaActionPerformed
        cardLayout.show(mainPanel, "panelMahasiswa");
    }//GEN-LAST:event_btnMahasiswaActionPerformed

    private void btnDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosenActionPerformed
        cardLayout.show(mainPanel, "panelDosen");
    }//GEN-LAST:event_btnDosenActionPerformed

    private void btnKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelasActionPerformed
        cardLayout.show(mainPanel, "panelKelas");
    }//GEN-LAST:event_btnKelasActionPerformed

    private void btnMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatkulActionPerformed
        cardLayout.show(mainPanel, "panelMatkul");
    }//GEN-LAST:event_btnMatkulActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        cardLayout.show(mainPanel, "panelJadwal");
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void btnAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsensiActionPerformed
        cardLayout.show(mainPanel, "panelAbsensi");
    }//GEN-LAST:event_btnAbsensiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
            new loginForm().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbsensi;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDosen;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnKelas;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMahasiswa;
    private javax.swing.JButton btnMatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
