/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.eabsensii.view;

import com.mycompany.eabsensii.EventBus;
import com.mycompany.eabsensii.dao.MataKuliahDAO;
import com.mycompany.eabsensii.model.MataKuliahModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaqy
 */
public class PanelMatkul extends javax.swing.JPanel implements EventBus.DataChangeListener {

    private final MataKuliahDAO matkulDAO;
    private List<MataKuliahModel> listMataKuliahData;
    private boolean isFirstTime = true;

    private boolean isEditing = false;
    private int editingIdMk = -1;

    public PanelMatkul() {
        initComponents();
        matkulDAO = new MataKuliahDAO();
        listMataKuliahData = new ArrayList<>();

        tblMataKuliah.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                loadFormDataToForm();
            }
        });

        txtCariNamaMataKuliah.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filterTable();
            }
        });
    }

    private void loadDataToTable() {
        listMataKuliahData = matkulDAO.getAllMataKuliah();
        DefaultTableModel model = (DefaultTableModel) tblMataKuliah.getModel();
        model.setRowCount(0);

        int no = 1;
        for (MataKuliahModel mk : listMataKuliahData) {
            Object[] rowData = {
                no++ + ".",
                mk.getNamaMk(),
                mk.getKodeMk(),
                mk.getSks()
            };
            model.addRow(rowData);
        }
    }

    private void clearForm() {
        txtNamaMataKuliah.setText("");
        txtKodeMK.setText("");
        txtJumlahSKS.setText("");
    }

    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag && isFirstTime) {
            loadDataToTable(); 
            isFirstTime = false; 
        }
    }

    private void loadFormDataToForm() {
        int selectedRow = tblMataKuliah.getSelectedRow();
        if (selectedRow != -1) {
            MataKuliahModel selectedMk = listMataKuliahData.get(selectedRow);

            txtNamaMataKuliah.setText(selectedMk.getNamaMk());
            txtKodeMK.setText(selectedMk.getKodeMk());
            txtJumlahSKS.setText(String.valueOf(selectedMk.getSks()));

            isEditing = true;
            editingIdMk = selectedMk.getIdMk();
        }
    }

    private void resetFormState() {
        clearForm();
        isEditing = false;
        editingIdMk = -1;
    }

    private void filterTable() {
        // 1. Ambil teks dari field pencarian
        String searchText = txtCariNamaMataKuliah.getText().trim().toLowerCase();

        // 2. Buat model baru
        DefaultTableModel filteredModel = new DefaultTableModel(
                new Object[][]{},
                new String[]{"No", "Nama Mata Kuliah", "Kode MK", "Jumlah SKS"}
        );

        // 3. Loop melalui data master
        int no = 1;
        for (MataKuliahModel mk : listMataKuliahData) {
            // 4. Cek apakah nama mata kuliah mengandung (case-insensitive)
            if (mk.getNamaMk().toLowerCase().contains(searchText)) {
                Object[] rowData = {
                    no++ + ".",
                    mk.getNamaMk(),
                    mk.getKodeMk(),
                    mk.getSks()
                };
                filteredModel.addRow(rowData);
            }
        }

        // 5. Set model baru ke tabel
        tblMataKuliah.setModel(filteredModel);
    }

    @Override
    public void onDataChanged() {
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMatkul = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblNamaMataKuliah = new javax.swing.JLabel();
        txtNamaMataKuliah = new javax.swing.JTextField();
        lblJumlahSKS1 = new javax.swing.JLabel();
        txtJumlahSKS = new javax.swing.JTextField();
        lblKodeMK = new javax.swing.JLabel();
        txtKodeMK = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();
        lblCariNamaMK = new javax.swing.JLabel();
        txtCariNamaMataKuliah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMataKuliah = new javax.swing.JTable();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Manajemen Data Mata Kuliah");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 20, 0));

        lblNamaMataKuliah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaMataKuliah.setText("Nama Mata Kuliah:");

        txtNamaMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaMataKuliahActionPerformed(evt);
            }
        });

        lblJumlahSKS1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahSKS1.setText("Jumlah SKS:");

        txtJumlahSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahSKSActionPerformed(evt);
            }
        });

        lblKodeMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKodeMK.setText("Kode MK:");

        btnTambah.setBackground(new java.awt.Color(0, 153, 153));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(0, 153, 153));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(0, 153, 153));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBersihkan.setBackground(new java.awt.Color(0, 153, 153));
        btnBersihkan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBersihkan.setForeground(new java.awt.Color(255, 255, 255));
        btnBersihkan.setText("Bersihkan");
        btnBersihkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        lblCariNamaMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCariNamaMK.setText("Cari Nama Mata Kuliah:");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblMataKuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "no", "Nama Mata Kuliah", "kode Mata Kuliah", "Jumlah SKS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMataKuliah.setColumnSelectionAllowed(true);
        tblMataKuliah.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMataKuliah);
        tblMataKuliah.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblMataKuliah.getColumnModel().getColumnCount() > 0) {
            tblMataKuliah.getColumnModel().getColumn(0).setMinWidth(30);
            tblMataKuliah.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblMataKuliah.getColumnModel().getColumn(0).setMaxWidth(30);
            tblMataKuliah.getColumnModel().getColumn(1).setMinWidth(400);
            tblMataKuliah.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblMataKuliah.getColumnModel().getColumn(1).setMaxWidth(400);
        }

        javax.swing.GroupLayout panelMatkulLayout = new javax.swing.GroupLayout(panelMatkul);
        panelMatkul.setLayout(panelMatkulLayout);
        panelMatkulLayout.setHorizontalGroup(
            panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatkulLayout.createSequentialGroup()
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMatkulLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel5))
                    .addGroup(panelMatkulLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelMatkulLayout.createSequentialGroup()
                                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNamaMataKuliah)
                                    .addComponent(lblJumlahSKS1)
                                    .addComponent(lblKodeMK))
                                .addGap(18, 18, 18)
                                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaMataKuliah, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(txtJumlahSKS)
                                    .addComponent(txtKodeMK)))
                            .addGroup(panelMatkulLayout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnBersihkan)
                                .addGap(45, 45, 45)
                                .addComponent(lblCariNamaMK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCariNamaMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelMatkulLayout.setVerticalGroup(
            panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatkulLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaMataKuliah)
                    .addComponent(txtNamaMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahSKS1))
                .addGap(18, 18, 18)
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKodeMK)
                    .addComponent(txtKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnBersihkan)
                    .addComponent(lblCariNamaMK)
                    .addComponent(txtCariNamaMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMataKuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMataKuliahActionPerformed

    private void txtJumlahSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahSKSActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // 1. validasi
        String namaMk = txtNamaMataKuliah.getText().trim();
        String kodeMk = txtKodeMK.getText().trim();
        String sksText = txtJumlahSKS.getText().trim();

        if (namaMk.isEmpty() || kodeMk.isEmpty() || sksText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int sks;
        try {
            sks = Integer.parseInt(sksText);
            if (sks <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah SKS harus angka positif!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah SKS harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Buat objek model
        MataKuliahModel newMk = new MataKuliahModel(kodeMk, namaMk, sks);

        // 3. Panggil DAO untuk menambah data
        boolean isSuccess = matkulDAO.addMataKuliah(newMk);

        // 4. Tampilkan pesan dan refresh
        if (isSuccess) {
            JOptionPane.showMessageDialog(this, "Data mata kuliah berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            clearForm();
            loadDataToTable();
            EventBus.notifyDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambah data. Kemungkinan kode mata kuliah sudah ada.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // 1. Validasi
        if (!isEditing) {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel terlebih dahulu sebelum mengubah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Ambil dan validasi
        String namaMk = txtNamaMataKuliah.getText().trim();
        String kodeMk = txtKodeMK.getText().trim();
        String sksText = txtJumlahSKS.getText().trim();

        if (namaMk.isEmpty() || kodeMk.isEmpty() || sksText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int sks;
        try {
            sks = Integer.parseInt(sksText);
            if (sks <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah SKS harus angka positif!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah SKS harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Buat objek model dan set ID-nya
        MataKuliahModel mkToUpdate = new MataKuliahModel(kodeMk, namaMk, sks);
        mkToUpdate.setIdMk(editingIdMk);

        // 4. Panggil DAO
        boolean isSuccess = matkulDAO.updateMataKuliah(mkToUpdate);

        // 5. Tampilkan pesan berdasarkan hasil
        if (isSuccess) {
            JOptionPane.showMessageDialog(this, "Data mata kuliah berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            resetFormState();
            loadDataToTable();
            EventBus.notifyDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data. Kemungkinan kode atau nama mata kuliah sudah digunakan.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // 1. Ambil baris yang di Highlight tabel
        int selectedRow = tblMataKuliah.getSelectedRow();

        // 2. Validasi
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data mata kuliah yang ingin dihapus terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Ambil data mata kuliah dari list yang dipilih
        MataKuliahModel selectedMk = listMataKuliahData.get(selectedRow);
        int idMk = selectedMk.getIdMk();
        String namaMk = selectedMk.getNamaMk();

        // 4. dialog konfirmasi
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menghapus mata kuliah '" + namaMk + "'?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        // 5. Confirmation
        if (confirm == JOptionPane.YES_OPTION) {
            matkulDAO.deleteMataKuliah(idMk);

            JOptionPane.showMessageDialog(this, "Data mata kuliah berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // 6. Refresh tampilan
            clearForm();
            loadDataToTable();
            EventBus.notifyDataChanged();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        resetFormState();
    }//GEN-LAST:event_btnBersihkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCariNamaMK;
    private javax.swing.JLabel lblJumlahSKS1;
    private javax.swing.JLabel lblKodeMK;
    private javax.swing.JLabel lblNamaMataKuliah;
    private javax.swing.JPanel panelMatkul;
    private javax.swing.JTable tblMataKuliah;
    private javax.swing.JTextField txtCariNamaMataKuliah;
    private javax.swing.JTextField txtJumlahSKS;
    private javax.swing.JTextField txtKodeMK;
    private javax.swing.JTextField txtNamaMataKuliah;
    // End of variables declaration//GEN-END:variables
}
