/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.eabsensii.view;

import com.mycompany.eabsensii.EventBus;
import com.mycompany.eabsensii.dao.DosenDAO;
import com.mycompany.eabsensii.model.DosenModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaqy
 */
public class PanelDosen extends javax.swing.JPanel implements EventBus.DataChangeListener {

    private final DosenDAO dosenDAO;
    private List<DosenModel> listDosenData;
    private boolean isFirstTime = true;

    private boolean isEditing = false;
    private int editingIdDosen = -1;

    public PanelDosen() {
        initComponents();
        dosenDAO = new DosenDAO();
        listDosenData = new ArrayList<>();

        tblDosen.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                loadFormDataToForm();
            }
        });

        txtCariNamaDosen.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filterTable();
            }
        });
    }

    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag && isFirstTime) {
            loadDataToTable();
            isFirstTime = false;
        }
    }

    private void loadDataToTable() {
        listDosenData = dosenDAO.getAllDosen();
        DefaultTableModel model = (DefaultTableModel) tblDosen.getModel();
        model.setRowCount(0);

        int no = 1;
        for (DosenModel dosen : listDosenData) {
            Object[] rowData = {
                no++ + ".",
                dosen.getNamaDosen(),
                dosen.getNidn()
            };
            model.addRow(rowData);
        }
    }

    private void clearForm() {
        txtNamaDosen.setText("");
        txtNidn.setText("");
    }

    private void loadFormDataToForm() {
        int selectedRow = tblDosen.getSelectedRow();
        if (selectedRow != -1) {
            // Ambil data dari list berdasarkan baris yang dipilih
            DosenModel selectedDosen = listDosenData.get(selectedRow);

            // Isi form dengan data
            txtNamaDosen.setText(selectedDosen.getNamaDosen());
            txtNidn.setText(selectedDosen.getNidn());

            // Aktifkan mode edit
            isEditing = true;
            editingIdDosen = selectedDosen.getIdDosen();
        }
    }

    private void resetFormState() {
        clearForm();
        isEditing = false; 
        editingIdDosen = -1; 
    }

    private void filterTable() {
        // 1. Ambil teks dari field pencarian
        String searchText = txtCariNamaDosen.getText().trim().toLowerCase();

        // 2. Buat model baru for tabel yang sudah difilter
        DefaultTableModel filteredModel = new DefaultTableModel(
                new Object[][]{},
                new String[]{"No.", "Nama Dosen", "NIDN"}
        );

        // 3. Loop melalui data master
        int no = 1;
        for (DosenModel dosen : listDosenData) {
            // 4. Cek apakah nama dosen mengandung teks pencarian
            if (dosen.getNamaDosen().toLowerCase().contains(searchText)) {
                Object[] rowData = {
                    no++ + ".",
                    dosen.getNamaDosen(),
                    dosen.getNidn()
                };
                filteredModel.addRow(rowData);
            }
        }

        // 5. Set model baru ke tabel
        tblDosen.setModel(filteredModel);
    }

    @Override
    public void onDataChanged() {
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDosen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblNamaDosen = new javax.swing.JLabel();
        txtNamaDosen = new javax.swing.JTextField();
        lblNidn = new javax.swing.JLabel();
        txtNidn = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();
        lblCariNamaDosen = new javax.swing.JLabel();
        txtCariNamaDosen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDosen = new javax.swing.JTable();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Manajemen Data Dosen");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 20, 0));

        lblNamaDosen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaDosen.setText("Nama Dosen:");

        lblNidn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNidn.setText("NIDN:");

        btnTambah.setBackground(new java.awt.Color(0, 153, 153));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(0, 153, 153));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(0, 153, 153));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBersihkan.setBackground(new java.awt.Color(0, 153, 153));
        btnBersihkan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBersihkan.setForeground(new java.awt.Color(255, 255, 255));
        btnBersihkan.setText("Bersihkan");
        btnBersihkan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        lblCariNamaDosen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCariNamaDosen.setText("Cari Nama Dosen:");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nama Dosen", "NIDN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDosen);
        if (tblDosen.getColumnModel().getColumnCount() > 0) {
            tblDosen.getColumnModel().getColumn(0).setMinWidth(40);
            tblDosen.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblDosen.getColumnModel().getColumn(0).setMaxWidth(40);
            tblDosen.getColumnModel().getColumn(1).setMinWidth(400);
            tblDosen.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblDosen.getColumnModel().getColumn(1).setMaxWidth(400);
        }

        javax.swing.GroupLayout panelDosenLayout = new javax.swing.GroupLayout(panelDosen);
        panelDosen.setLayout(panelDosenLayout);
        panelDosenLayout.setHorizontalGroup(
            panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosenLayout.createSequentialGroup()
                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDosenLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel5))
                    .addGroup(panelDosenLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDosenLayout.createSequentialGroup()
                                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNamaDosen)
                                    .addComponent(lblNidn)
                                    .addComponent(btnTambah))
                                .addGap(18, 18, 18)
                                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDosenLayout.createSequentialGroup()
                                        .addComponent(btnUbah)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBersihkan)
                                        .addGap(54, 54, 54)
                                        .addComponent(lblCariNamaDosen)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCariNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNamaDosen, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNidn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelDosenLayout.setVerticalGroup(
            panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosenLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaDosen)
                    .addComponent(txtNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNidn)
                    .addComponent(txtNidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnBersihkan)
                    .addComponent(lblCariNamaDosen)
                    .addComponent(txtCariNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // 1. Ambil dan validasi data dari form
        String namaDosen = txtNamaDosen.getText().trim();
        String nidn = txtNidn.getText().trim();

        if (namaDosen.isEmpty() || nidn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Dosen dan NIDN harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Buat objek model
        DosenModel newDosen = new DosenModel(nidn, namaDosen);

        // 3. Panggil DAO untuk menambah data
        boolean isSuccess = dosenDAO.addDosen(newDosen);

        // 4. Tampilkan pesan dan refresh
        if (isSuccess) {
            JOptionPane.showMessageDialog(this, "Data dosen berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            clearForm();
            loadDataToTable();
            EventBus.notifyDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambah data. Kemungkinan NIDN sudah terdaftar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // 1. Validasi
        if (!isEditing) {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel terlebih dahulu sebelum mengubah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Ambil dan validasi data dari form
        String namaDosen = txtNamaDosen.getText().trim();
        String nidn = txtNidn.getText().trim();

        if (namaDosen.isEmpty() || nidn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Dosen dan NIDN harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Buat objek model dan set ID-nya
        DosenModel dosenToUpdate = new DosenModel(nidn, namaDosen);
        dosenToUpdate.setIdDosen(editingIdDosen);

        // 4. Panggil DAO untuk mengupdate data
        boolean isSuccess = dosenDAO.updateDosen(dosenToUpdate);

        // 5. Tampilkan pesan berdasarkan hasil
        if (isSuccess) {
            JOptionPane.showMessageDialog(this, "Data dosen berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            resetFormState();
            loadDataToTable();
            EventBus.notifyDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data. Kemungkinan NIDN sudah digunakan.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // 1. Ambil baris yang dipilih di tabel
        int selectedRow = tblDosen.getSelectedRow();

        // 2. Validasi
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dosen yang ingin dihapus terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Ambil data dosen dari list berdasarkan baris yang dipilih
        DosenModel selectedDosen = listDosenData.get(selectedRow);
        int idDosen = selectedDosen.getIdDosen();
        String namaDosen = selectedDosen.getNamaDosen();

        // 4. Tampilkan dialog konfirmasi
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin menghapus dosen '" + namaDosen + "'?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        // 5. Jika user menekan tombol "YES"
        if (confirm == JOptionPane.YES_OPTION) {
            // Hapus data melalui DAO
            dosenDAO.deleteDosen(idDosen);

            // Tampilkan pesan sukses
            JOptionPane.showMessageDialog(this, "Data dosen berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // 6. Refresh tampilan
            clearForm();
            loadDataToTable();
            EventBus.notifyDataChanged();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        resetFormState();
    }//GEN-LAST:event_btnBersihkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCariNamaDosen;
    private javax.swing.JLabel lblNamaDosen;
    private javax.swing.JLabel lblNidn;
    private javax.swing.JPanel panelDosen;
    private javax.swing.JTable tblDosen;
    private javax.swing.JTextField txtCariNamaDosen;
    private javax.swing.JTextField txtNamaDosen;
    private javax.swing.JTextField txtNidn;
    // End of variables declaration//GEN-END:variables
}
