/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.eabsensii.view;

import com.mycompany.eabsensii.EventBus;
import com.mycompany.eabsensii.dao.AbsensiDAO;
import com.mycompany.eabsensii.dao.DashboardDAO;
import com.mycompany.eabsensii.dao.JadwalDAO;
import com.mycompany.eabsensii.dao.KelasDAO;
import com.mycompany.eabsensii.dao.MahasiswaDAO;
import com.mycompany.eabsensii.model.AbsensiModel;
import com.mycompany.eabsensii.model.DashboardModel;
import com.mycompany.eabsensii.model.JadwalModel;
import com.mycompany.eabsensii.model.KelasExportModel;
import com.mycompany.eabsensii.model.MahasiswaModel;
import com.mycompany.eabsensii.model.MataKuliahModel;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author shaqy
 */
public class PanelDashboard extends javax.swing.JPanel implements EventBus.DataChangeListener {

    private DashboardDAO dashboardDAO;
    
    public PanelDashboard() {
        initComponents();

        dashboardDAO = new DashboardDAO(); 
        EventBus.subscribe(this);
        loadDashboardData();               

        txtTotalMahasiswa.setEditable(false);
        txtTotalDosen.setEditable(false);
        txtTotalKelas.setEditable(false);
        txtTingkatKehadiranBulanIni.setEditable(false);
    }

    private void loadDashboardData() {
        // 1. Ambil data stats dari DAO
        DashboardModel stats = dashboardDAO.getDashboardStats();

        // 2. Tampilkan data ke JTextField
        txtTotalMahasiswa.setText(String.valueOf(stats.getTotalMahasiswa()));
        txtTotalDosen.setText(String.valueOf(stats.getTotalDosen()));
        txtTotalKelas.setText(String.valueOf(stats.getTotalKelas()));

        // 3. format dua angka dibelakang koma
        double kehadiran = stats.getTingkatKehadiranBulanIni();
        txtTingkatKehadiranBulanIni.setText(String.format("%.2f%%", kehadiran));
    }

    @Override
    public void onDataChanged() {
        loadDashboardData();
    }

    @Override
    public void removeNotify() {
        super.removeNotify();
        EventBus.unsubscribe(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlTotalMahasiswa = new javax.swing.JPanel();
        lblTotalMahasiswa = new javax.swing.JLabel();
        txtTotalMahasiswa = new javax.swing.JTextField();
        pnlTotalDosen = new javax.swing.JPanel();
        lblTotalDosen = new javax.swing.JLabel();
        txtTotalDosen = new javax.swing.JTextField();
        pnlTotalKelas = new javax.swing.JPanel();
        lblTotalKelas = new javax.swing.JLabel();
        txtTotalKelas = new javax.swing.JTextField();
        pnlTingkatKehadiranBulanIni = new javax.swing.JPanel();
        lblTingkatKehadiranBulanIni = new javax.swing.JLabel();
        txtTingkatKehadiranBulanIni = new javax.swing.JTextField();
        lblExportDataMahasiswa = new javax.swing.JLabel();
        lblExportDataKelas = new javax.swing.JLabel();
        lblExportDataMatakuliah = new javax.swing.JLabel();
        lblExportDataJadwalKelas = new javax.swing.JLabel();
        lblExportDataAbsensi = new javax.swing.JLabel();
        btnExportDataMahasiswa = new javax.swing.JButton();
        btnExportDataKelas = new javax.swing.JButton();
        btnExportDataMatakuliah = new javax.swing.JButton();
        btnExportDataJadwalKelas = new javax.swing.JButton();
        btnExportDataAbsensi = new javax.swing.JButton();

        panelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Dashboard");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 20, 0));

        pnlTotalMahasiswa.setBackground(new java.awt.Color(0, 153, 153));

        lblTotalMahasiswa.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalMahasiswa.setText("Total Mahasiswa");

        txtTotalMahasiswa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMahasiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTotalMahasiswaLayout = new javax.swing.GroupLayout(pnlTotalMahasiswa);
        pnlTotalMahasiswa.setLayout(pnlTotalMahasiswaLayout);
        pnlTotalMahasiswaLayout.setHorizontalGroup(
            pnlTotalMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalMahasiswaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlTotalMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTotalMahasiswa)
                    .addComponent(lblTotalMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlTotalMahasiswaLayout.setVerticalGroup(
            pnlTotalMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(txtTotalMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlTotalDosen.setBackground(new java.awt.Color(0, 153, 153));

        lblTotalDosen.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalDosen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalDosen.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalDosen.setText("Total Dosen");

        txtTotalDosen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalDosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTotalDosenLayout = new javax.swing.GroupLayout(pnlTotalDosen);
        pnlTotalDosen.setLayout(pnlTotalDosenLayout);
        pnlTotalDosenLayout.setHorizontalGroup(
            pnlTotalDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalDosenLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlTotalDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTotalDosen)
                    .addComponent(lblTotalDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlTotalDosenLayout.setVerticalGroup(
            pnlTotalDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalDosen)
                .addGap(18, 18, 18)
                .addComponent(txtTotalDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlTotalKelas.setBackground(new java.awt.Color(0, 153, 153));

        lblTotalKelas.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalKelas.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalKelas.setText("Total Kelas");

        txtTotalKelas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTotalKelasLayout = new javax.swing.GroupLayout(pnlTotalKelas);
        pnlTotalKelas.setLayout(pnlTotalKelasLayout);
        pnlTotalKelasLayout.setHorizontalGroup(
            pnlTotalKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalKelasLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlTotalKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTotalKelas)
                    .addComponent(lblTotalKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlTotalKelasLayout.setVerticalGroup(
            pnlTotalKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalKelas)
                .addGap(18, 18, 18)
                .addComponent(txtTotalKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlTingkatKehadiranBulanIni.setBackground(new java.awt.Color(0, 153, 153));

        lblTingkatKehadiranBulanIni.setBackground(new java.awt.Color(255, 255, 255));
        lblTingkatKehadiranBulanIni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTingkatKehadiranBulanIni.setForeground(new java.awt.Color(255, 255, 255));
        lblTingkatKehadiranBulanIni.setText("Tingkat Kehadiran Bulan Ini");

        txtTingkatKehadiranBulanIni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTingkatKehadiranBulanIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTingkatKehadiranBulanIniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTingkatKehadiranBulanIniLayout = new javax.swing.GroupLayout(pnlTingkatKehadiranBulanIni);
        pnlTingkatKehadiranBulanIni.setLayout(pnlTingkatKehadiranBulanIniLayout);
        pnlTingkatKehadiranBulanIniLayout.setHorizontalGroup(
            pnlTingkatKehadiranBulanIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTingkatKehadiranBulanIniLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlTingkatKehadiranBulanIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTingkatKehadiranBulanIni)
                    .addComponent(lblTingkatKehadiranBulanIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlTingkatKehadiranBulanIniLayout.setVerticalGroup(
            pnlTingkatKehadiranBulanIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTingkatKehadiranBulanIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTingkatKehadiranBulanIni)
                .addGap(18, 18, 18)
                .addComponent(txtTingkatKehadiranBulanIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        lblExportDataMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExportDataMahasiswa.setText("Export Data Mahasiswa:");

        lblExportDataKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExportDataKelas.setText("Export Data Kelas:");

        lblExportDataMatakuliah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExportDataMatakuliah.setText("Export Data Matakuliah:");

        lblExportDataJadwalKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExportDataJadwalKelas.setText("Export Data Jadwal Kelas:");

        lblExportDataAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExportDataAbsensi.setText("Export Data Absensi:");

        btnExportDataMahasiswa.setBackground(new java.awt.Color(0, 153, 153));
        btnExportDataMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExportDataMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnExportDataMahasiswa.setText("Export");
        btnExportDataMahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportDataMahasiswaActionPerformed(evt);
            }
        });

        btnExportDataKelas.setBackground(new java.awt.Color(0, 153, 153));
        btnExportDataKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExportDataKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnExportDataKelas.setText("Export");
        btnExportDataKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportDataKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportDataKelasActionPerformed(evt);
            }
        });

        btnExportDataMatakuliah.setBackground(new java.awt.Color(0, 153, 153));
        btnExportDataMatakuliah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExportDataMatakuliah.setForeground(new java.awt.Color(255, 255, 255));
        btnExportDataMatakuliah.setText("Export");
        btnExportDataMatakuliah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportDataMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportDataMatakuliahActionPerformed(evt);
            }
        });

        btnExportDataJadwalKelas.setBackground(new java.awt.Color(0, 153, 153));
        btnExportDataJadwalKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExportDataJadwalKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnExportDataJadwalKelas.setText("Export");
        btnExportDataJadwalKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportDataJadwalKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportDataJadwalKelasActionPerformed(evt);
            }
        });

        btnExportDataAbsensi.setBackground(new java.awt.Color(0, 153, 153));
        btnExportDataAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExportDataAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        btnExportDataAbsensi.setText("Export");
        btnExportDataAbsensi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportDataAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportDataAbsensiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel5))
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDashboardLayout.createSequentialGroup()
                                .addComponent(pnlTotalMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlTotalDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlTotalKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlTingkatKehadiranBulanIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDashboardLayout.createSequentialGroup()
                                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblExportDataJadwalKelas)
                                    .addComponent(lblExportDataAbsensi)
                                    .addComponent(lblExportDataMatakuliah)
                                    .addComponent(lblExportDataKelas)
                                    .addComponent(lblExportDataMahasiswa))
                                .addGap(18, 18, 18)
                                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExportDataMahasiswa)
                                    .addComponent(btnExportDataKelas)
                                    .addComponent(btnExportDataMatakuliah)
                                    .addComponent(btnExportDataAbsensi)
                                    .addComponent(btnExportDataJadwalKelas))))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTotalMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDashboardLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlTotalDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlTotalKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlTingkatKehadiranBulanIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExportDataMahasiswa)
                    .addComponent(btnExportDataMahasiswa))
                .addGap(18, 18, 18)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExportDataKelas)
                    .addComponent(btnExportDataKelas))
                .addGap(18, 18, 18)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExportDataMatakuliah)
                    .addComponent(btnExportDataMatakuliah))
                .addGap(18, 18, 18)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExportDataJadwalKelas)
                    .addComponent(btnExportDataJadwalKelas))
                .addGap(18, 18, 18)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExportDataAbsensi)
                    .addComponent(btnExportDataAbsensi))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTingkatKehadiranBulanIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTingkatKehadiranBulanIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTingkatKehadiranBulanIniActionPerformed

    private void txtTotalMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMahasiswaActionPerformed

    private void txtTotalDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalDosenActionPerformed

    private void txtTotalKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKelasActionPerformed

    private void btnExportDataJadwalKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportDataJadwalKelasActionPerformed
        // 1. Buka dialog untuk simpan file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Jadwal Kelas");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File fileToSave = fileChooser.getSelectedFile();
        // File MUST .xlsx
        if (!fileToSave.getName().toLowerCase().endsWith(".xlsx")) {
            fileToSave = new File(fileToSave.getParentFile(), fileToSave.getName() + ".xlsx");
        }

        // 2. Ambil data jadwal per kelas dari DAO
        JadwalDAO jadwalDAO = new JadwalDAO();
        Map<String, List<JadwalModel>> dataPerKelas = jadwalDAO.getAllJadwalGroupedByClass();

        if (dataPerKelas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak ada data jadwal untuk diekspor.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // 3. Proses buatan file Excel
        try (XSSFWorkbook workbook = new XSSFWorkbook(); FileOutputStream outputStream = new FileOutputStream(fileToSave)) {

            // 4. Iterasi setiap kelas dan buat sheet-nya
            for (Map.Entry<String, List<JadwalModel>> entry : dataPerKelas.entrySet()) {
                String namaKelas = entry.getKey();
                List<JadwalModel> listJadwal = entry.getValue();

                // Buat sheet dengan nama kelas
                String sheetName = namaKelas.length() > 31 ? namaKelas.substring(0, 31) : namaKelas;
                XSSFSheet sheet = workbook.createSheet(sheetName);

                // 5. Buat baris header
                XSSFRow headerRow = sheet.createRow(0);
                headerRow.createCell(0).setCellValue("No.");
                headerRow.createCell(1).setCellValue("Mata Kuliah");
                headerRow.createCell(2).setCellValue("Hari");
                headerRow.createCell(3).setCellValue("Jam Mulai");
                headerRow.createCell(4).setCellValue("Jam Selesai");
                headerRow.createCell(5).setCellValue("Dosen");

                // 6. Isi data jadwal
                int no = 1;
                for (int i = 0; i < listJadwal.size(); i++) {
                    JadwalModel jadwal = listJadwal.get(i);
                    XSSFRow dataRow = sheet.createRow(no); // Baris dimulai dari indeks 1

                    dataRow.createCell(0).setCellValue(no);
                    dataRow.createCell(1).setCellValue(jadwal.getNamaMatakuliah());
                    dataRow.createCell(2).setCellValue(jadwal.getHari());
                    dataRow.createCell(3).setCellValue(jadwal.getJam_mulai());
                    dataRow.createCell(4).setCellValue(jadwal.getJam_selesai());
                    dataRow.createCell(5).setCellValue(jadwal.getNamaDosen());
                    no++;
                }

                // 7. Auto-size kolom
                sheet.autoSizeColumn(0);
                sheet.autoSizeColumn(1);
                sheet.autoSizeColumn(2);
                sheet.autoSizeColumn(3);
                sheet.autoSizeColumn(4);
                sheet.autoSizeColumn(5);
            }

            // 8. Tulis workbook ke file
            workbook.write(outputStream);

            JOptionPane.showMessageDialog(this, "Data jadwal kelas berhasil diekspor ke:\n" + fileToSave.getAbsolutePath(), "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            System.err.println("Error saat mengekspor ke Excel: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Gagal mengekspor data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        EventBus.notifyDataChanged();
    }//GEN-LAST:event_btnExportDataJadwalKelasActionPerformed

    private void btnExportDataAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportDataAbsensiActionPerformed
        // 1. Buka dialog untuk simpan file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Absensi");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File fileToSave = fileChooser.getSelectedFile();
        if (!fileToSave.getName().toLowerCase().endsWith(".xlsx")) {
            fileToSave = new File(fileToSave.getParentFile(), fileToSave.getName() + ".xlsx");
        }

        // 2. Ambil data absensi per kelas dari DAO
        AbsensiDAO absensiDAO = new AbsensiDAO();
        Map<String, List<AbsensiModel>> dataPerKelas = absensiDAO.getAllAbsensiGroupedByClass();

        if (dataPerKelas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak ada data absensi untuk diekspor.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // 3. Proses buatan file Excel
        try (XSSFWorkbook workbook = new XSSFWorkbook(); FileOutputStream outputStream = new FileOutputStream(fileToSave)) {

            // 4. Iterasi setiap kelas dan buat sheet-nya
            for (Map.Entry<String, List<AbsensiModel>> entry : dataPerKelas.entrySet()) {
                String namaKelas = entry.getKey();
                List<AbsensiModel> listAbsensi = entry.getValue();

                // Urutkan data absensi berdasarkan nama mata kuliah
                listAbsensi.sort((a1, a2) -> a1.getNamaJadwalFormatted().compareToIgnoreCase(a2.getNamaJadwalFormatted()));

                // Buat sheet dengan nama kelas
                String sheetName = namaKelas.length() > 31 ? namaKelas.substring(0, 31) : namaKelas;
                XSSFSheet sheet = workbook.createSheet(sheetName);

                // 5. Buat baris header
                XSSFRow headerRow = sheet.createRow(0);
                headerRow.createCell(0).setCellValue("No.");
                headerRow.createCell(1).setCellValue("Nama Mahasiswa");
                headerRow.createCell(2).setCellValue("NIM");
                headerRow.createCell(3).setCellValue("Jadwal");
                headerRow.createCell(4).setCellValue("Tanggal");
                headerRow.createCell(5).setCellValue("Status");
                headerRow.createCell(6).setCellValue("Jam Masuk");
                headerRow.createCell(7).setCellValue("Keterangan");

                // 6. Isi data absensi
                int no = 1;
                for (int i = 0; i < listAbsensi.size(); i++) {
                    AbsensiModel absensi = listAbsensi.get(i);
                    XSSFRow dataRow = sheet.createRow(no);

                    dataRow.createCell(0).setCellValue(no);
                    dataRow.createCell(1).setCellValue(absensi.getNamaMahasiswaFormatted());

                    // Extract NIM dari string "NIM - Nama Mahasiswa"
                    String nim = absensi.getNamaMahasiswaFormatted().split(" - ")[0];
                    dataRow.createCell(2).setCellValue(nim);

                    dataRow.createCell(3).setCellValue(absensi.getNamaJadwalFormatted());
                    dataRow.createCell(4).setCellValue(absensi.getTanggal_absensi()); // <-- KOLOM BARU
                    dataRow.createCell(5).setCellValue(absensi.getStatus());

                    // Format Timestamp menjadi String "HH:mm:ss"
                    String jamMasukFormatted = "";
                    if (absensi.getJam_masuk() != null) {
                        jamMasukFormatted = new java.text.SimpleDateFormat("HH:mm:ss").format(absensi.getJam_masuk());
                    }
                    dataRow.createCell(6).setCellValue(jamMasukFormatted);

                    dataRow.createCell(7).setCellValue(absensi.getKeterangan());
                    no++;
                }

                // 7. Auto-size kolom agar lebih mudah dibaca
                for (int i = 0; i < 8; i++) {
                    sheet.autoSizeColumn(i);
                }
            }

            // 8. Tulis workbook ke file
            workbook.write(outputStream);

            JOptionPane.showMessageDialog(this, "Data absensi berhasil diekspor ke:\n" + fileToSave.getAbsolutePath(), "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            System.err.println("Error saat mengekspor ke Excel: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Gagal mengekspor data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        EventBus.notifyDataChanged();
    }//GEN-LAST:event_btnExportDataAbsensiActionPerformed

    private void btnExportDataMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportDataMatakuliahActionPerformed
        // 1. Buka dialog untuk simpan file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Mata Kuliah");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File fileToSave = fileChooser.getSelectedFile();
        if (!fileToSave.getName().toLowerCase().endsWith(".xlsx")) {
            fileToSave = new File(fileToSave.getParentFile(), fileToSave.getName() + ".xlsx");
        }

        // 2. Ambil data mata kuliah per prodi dari DAO
        JadwalDAO jadwalDAO = new JadwalDAO();
        Map<String, List<MataKuliahModel>> dataPerProdi = jadwalDAO.getAllMataKuliahGroupedByProdi();

        if (dataPerProdi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak ada data mata kuliah untuk diekspor.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // 3. Proses buatan file Excel
        try (XSSFWorkbook workbook = new XSSFWorkbook(); FileOutputStream outputStream = new FileOutputStream(fileToSave)) {

            for (Map.Entry<String, List<MataKuliahModel>> entry : dataPerProdi.entrySet()) {
                String namaProdi = entry.getKey();
                List<MataKuliahModel> listMataKuliah = entry.getValue();

                String sheetName = namaProdi.length() > 31 ? namaProdi.substring(0, 31) : namaProdi;
                XSSFSheet sheet = workbook.createSheet(sheetName);

                // 5. Buat baris header
                XSSFRow headerRow = sheet.createRow(0);
                headerRow.createCell(0).setCellValue("No");
                headerRow.createCell(1).setCellValue("Mata Kuliah");
                headerRow.createCell(2).setCellValue("Kode Mata Kuliah");
                headerRow.createCell(3).setCellValue("Jumlah SKS");

                // 6. Isi data mahasiswa
                int no = 1;
                for (int i = 0; i < listMataKuliah.size(); i++) {
                    MataKuliahModel mk = listMataKuliah.get(i);
                    XSSFRow dataRow = sheet.createRow(no);

                    dataRow.createCell(0).setCellValue(no);
                    dataRow.createCell(1).setCellValue(mk.getNamaMk());
                    dataRow.createCell(2).setCellValue(mk.getKodeMk());
                    dataRow.createCell(3).setCellValue(mk.getSks());
                }

                // 7. Auto-size kolom
                sheet.autoSizeColumn(0);
                sheet.autoSizeColumn(1);
                sheet.autoSizeColumn(2);
                sheet.autoSizeColumn(3);
            }

            workbook.write(outputStream);
            JOptionPane.showMessageDialog(this, "Data mata kuliah berhasil diekspor ke:\n" + fileToSave.getAbsolutePath(), "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            System.err.println("Error saat mengekspor ke Excel: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Gagal mengekspor data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        EventBus.notifyDataChanged();
    }//GEN-LAST:event_btnExportDataMatakuliahActionPerformed

    private void btnExportDataKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportDataKelasActionPerformed
        // 1. Buka dialog untuk simpan file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Kelas");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File fileToSave = fileChooser.getSelectedFile();
        // File MUST .xlsx
        if (!fileToSave.getName().toLowerCase().endsWith(".xlsx")) {
            fileToSave = new File(fileToSave.getParentFile(), fileToSave.getName() + ".xlsx");
        }

        // 2. Ambil data dari DAO
        KelasDAO kelasDAO = new KelasDAO();
        List<KelasExportModel> dataForExport = kelasDAO.getAllKelasWithStudentCount();

        if (dataForExport.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak ada data kelas untuk diekspor.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // 3. Proses buatan file Excel
        try (XSSFWorkbook workbook = new XSSFWorkbook(); FileOutputStream outputStream = new FileOutputStream(fileToSave)) {

            // 4. Buat satu sheet = "Data Kelas"
            XSSFSheet sheet = workbook.createSheet("Data Kelas");

            // 5. Buat baris header
            XSSFRow headerRow = sheet.createRow(0);
            headerRow.createCell(0).setCellValue("No");
            headerRow.createCell(1).setCellValue("Nama Kelas");
            headerRow.createCell(2).setCellValue("Program Studi");
            headerRow.createCell(3).setCellValue("Tahun");
            headerRow.createCell(4).setCellValue("Total Mahasiswa Dalam Kelas");

            // 6. Isi data mahasiswa
            int no = 1;
            for (int i = 0; i < dataForExport.size(); i++) {
                KelasExportModel kelas = dataForExport.get(i);
                XSSFRow dataRow = sheet.createRow(no);

                dataRow.createCell(0).setCellValue(no);
                dataRow.createCell(1).setCellValue(kelas.getNamaKelas());
                dataRow.createCell(2).setCellValue(kelas.getNamaProdi());
                dataRow.createCell(3).setCellValue(kelas.getTahun());
                dataRow.createCell(4).setCellValue(kelas.getTotalMahasiswa());
                no++;
            }

            // 7. Auto-size kolom agar lebih mudah dibaca
            sheet.autoSizeColumn(0);
            sheet.autoSizeColumn(1);
            sheet.autoSizeColumn(2);
            sheet.autoSizeColumn(3);
            sheet.autoSizeColumn(4);

            // 8. Tulis workbook ke file
            workbook.write(outputStream);

            JOptionPane.showMessageDialog(this, "Data kelas berhasil diekspor ke:\n" + fileToSave.getAbsolutePath(), "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            System.err.println("Error saat mengekspor ke Excel: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Gagal mengekspor data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        EventBus.notifyDataChanged();
    }//GEN-LAST:event_btnExportDataKelasActionPerformed

    private void btnExportDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportDataMahasiswaActionPerformed
        // 1. Buka dialog untuk simpan file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Mahasiswa");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File fileToSave = fileChooser.getSelectedFile();
        // File MUST .xlsx
        if (!fileToSave.getName().toLowerCase().endsWith(".xlsx")) {
            fileToSave = new File(fileToSave.getParentFile(), fileToSave.getName() + ".xlsx");
        }

        // 2. Ambil data mahasiswa per kelas dari DAO
        MahasiswaDAO mahasiswaDAO = new MahasiswaDAO();
        Map<String, List<MahasiswaModel>> dataPerKelas = mahasiswaDAO.getAllMahasiswaGroupedByClass();

        if (dataPerKelas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak ada data mahasiswa untuk diekspor.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // 3. Proses buatan file Excel
        try (XSSFWorkbook workbook = new XSSFWorkbook(); FileOutputStream outputStream = new FileOutputStream(fileToSave)) {

            // 4. Iterasi setiap kelas dan buat sheet-nya
            for (Map.Entry<String, List<MahasiswaModel>> entry : dataPerKelas.entrySet()) {
                String namaKelas = entry.getKey();
                List<MahasiswaModel> listMahasiswa = entry.getValue();

                // Buat sheet dengan nama kelas
                String sheetName = namaKelas.length() > 31 ? namaKelas.substring(0, 31) : namaKelas;
                XSSFSheet sheet = workbook.createSheet(sheetName);

                // 5. Buat baris header
                XSSFRow headerRow = sheet.createRow(0);
                headerRow.createCell(0).setCellValue("No");
                headerRow.createCell(1).setCellValue("Nama Mahasiswa");
                headerRow.createCell(2).setCellValue("NIM");

                // 6. Isi data mahasiswa
                int no = 1;
                for (int i = 0; i < listMahasiswa.size(); i++) {
                    MahasiswaModel mhs = listMahasiswa.get(i);
                    XSSFRow dataRow = sheet.createRow(no);

                    dataRow.createCell(0).setCellValue(no);
                    dataRow.createCell(1).setCellValue(mhs.getNamaMahasiswa());
                    dataRow.createCell(2).setCellValue(mhs.getNim());
                    no++;
                }

                // 7. Auto-size kolom agar lebih mudah dibaca
                sheet.autoSizeColumn(0);
                sheet.autoSizeColumn(1);
                sheet.autoSizeColumn(2);
            }

            // 8. Tulis workbook ke file
            workbook.write(outputStream);

            JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diekspor ke:\n" + fileToSave.getAbsolutePath(), "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            System.err.println("Error saat mengekspor ke Excel: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Gagal mengekspor data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        EventBus.notifyDataChanged();
    }//GEN-LAST:event_btnExportDataMahasiswaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportDataAbsensi;
    private javax.swing.JButton btnExportDataJadwalKelas;
    private javax.swing.JButton btnExportDataKelas;
    private javax.swing.JButton btnExportDataMahasiswa;
    private javax.swing.JButton btnExportDataMatakuliah;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblExportDataAbsensi;
    private javax.swing.JLabel lblExportDataJadwalKelas;
    private javax.swing.JLabel lblExportDataKelas;
    private javax.swing.JLabel lblExportDataMahasiswa;
    private javax.swing.JLabel lblExportDataMatakuliah;
    private javax.swing.JLabel lblTingkatKehadiranBulanIni;
    private javax.swing.JLabel lblTotalDosen;
    private javax.swing.JLabel lblTotalKelas;
    private javax.swing.JLabel lblTotalMahasiswa;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel pnlTingkatKehadiranBulanIni;
    private javax.swing.JPanel pnlTotalDosen;
    private javax.swing.JPanel pnlTotalKelas;
    private javax.swing.JPanel pnlTotalMahasiswa;
    private javax.swing.JTextField txtTingkatKehadiranBulanIni;
    private javax.swing.JTextField txtTotalDosen;
    private javax.swing.JTextField txtTotalKelas;
    private javax.swing.JTextField txtTotalMahasiswa;
    // End of variables declaration//GEN-END:variables
}
